### ISSUE TITLE
Not able to use after Node.js update v20.9.0

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fdp-play#106]
Any command gives a long log, exactly the 
.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3

and in the end: 

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at 479 (/Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:1308071)
    at r (/Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:1496486)
    at /Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:1497191
    at /Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:1497414
    at /Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:1497421
    at /Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:81
    at Object.<anonymous> (/Users/t6/.nvm/versions/node/v20.9.0/lib/node_modules/@fairdatasociety/fdp-play/dist/index.js:3:237)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)

Node.js v20.9.0

**Comment by tamas6** [comment]
**Attempt to fix:** returning to node v16 start commands (and most) are working **but** the followings are not 
fdp-play start +
--bee-version
 --bee-repo
--fairos-image
--blockchain-image


giving the stated error above

**Comment by tfius** [comment]
Seems there are issues with fdp-play and latest bee. Can you try previous versions of fdp-play and node 18 ?
